name: Build and Release

on:
  push:
    tags:
      - 'v*'
      - '*.*.*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: |
        msbuild rtx-launcher\rtx-launcher.vcxproj /p:Configuration=Release /p:Platform=x64
        msbuild rtx-installer\rtx-installer.vcxproj /p:Configuration=Release /p:Platform=x64
      
    - name: Extract Version
      id: extract_version
      run: |
        $versionLine = Get-Content rtx-launcher\LauncherUpdater.h | Select-String 'CURRENT_VERSION ='
        $version = $versionLine -replace '.*L"([^"]+)".*', '$1'
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Release to GitHub
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
      with:
        tag_name: ${{ github.event_name == 'workflow_dispatch' && '0.0.2' || github.ref_name }}
        name: v${{ env.VERSION }}-Beta
        files: |
          rtx-installer/x64/Release/rtx-installer.exe
          rtx-launcher/x64/Release/system_data.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
